name: profile-site-infrastructure
description: DevOps Profile Site Infrastructure
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
